### ISSUE TITLE
(Codegen) stdint visual studio

### ISSUE THREAD

**Issue by orlyn44** [preesm/preesm#89]
On auto generation of preesm files in windows there are some error for visual 2015.

in preesm_gen.h and dump.h this should be changed:

from:
```C
#include <stdint.h> 
```

--------------------------------

to:
```C
#ifdef _MSC_VER
typedef _int32 int32_t;
typedef unsigned _int32 uint32_t;
#ifdef int64_t
#undef int64_t
typedef _int64 int64_t;
#endif 
#ifdef uint64_t
#undef uint64_t
typedef  unsigned _int64 uint64_t;
#endif

#else 
#include <stdint.h>
#endif  
```

**Comment by antoine-morvan** [comment]
Fixed in develop.

**Comment by orlyn44** [comment]
Codegen for visual still not working properly.
The following
```
#ifdef int64_t
#undef int64_t
typedef _int64 int64_t;
#endif 
#ifdef uint64_t
#undef uint64_t
typedef  unsigned _int64 uint64_t;
#endif
```
should be changed to 
```
#ifdef int64_t
#undef int64_t
#endif 
typedef _int64 int64_t;
#ifdef uint64_t
#undef uint64_t
#endif
typedef  unsigned _int64 uint64_t;
```

**Comment by antoine-morvan** [comment]
Fixed on develop.
